## PRE PROCESSING


In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [7]:
## ohe
one_hot_repr=[one_hot(words, voc_size)for words in sent]
one_hot_repr


[[9607, 1817, 6254, 9620],
 [9607, 1817, 6254, 4560],
 [9607, 8148, 6254, 7971],
 [7305, 5901, 1965, 5511, 2270],
 [7305, 5901, 1965, 5511, 7033],
 [6870, 9607, 9990, 6254, 4228],
 [1924, 7826, 890, 5511]]

In [8]:
## embedding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9607 1817 6254 9620]
 [   0    0    0    0 9607 1817 6254 4560]
 [   0    0    0    0 9607 8148 6254 7971]
 [   0    0    0 7305 5901 1965 5511 2270]
 [   0    0    0 7305 5901 1965 5511 7033]
 [   0    0    0 6870 9607 9990 6254 4228]
 [   0    0    0    0 1924 7826  890 5511]]


In [13]:
## feature representation
dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 349ms/step


array([[[ 9.40507650e-03, -4.40876596e-02, -2.81768572e-02,
          2.11584680e-02, -6.13879040e-03,  6.09459728e-03,
         -2.07377560e-02, -1.29706636e-02,  3.82832922e-02,
         -3.01131494e-02],
        [ 9.40507650e-03, -4.40876596e-02, -2.81768572e-02,
          2.11584680e-02, -6.13879040e-03,  6.09459728e-03,
         -2.07377560e-02, -1.29706636e-02,  3.82832922e-02,
         -3.01131494e-02],
        [ 9.40507650e-03, -4.40876596e-02, -2.81768572e-02,
          2.11584680e-02, -6.13879040e-03,  6.09459728e-03,
         -2.07377560e-02, -1.29706636e-02,  3.82832922e-02,
         -3.01131494e-02],
        [ 9.40507650e-03, -4.40876596e-02, -2.81768572e-02,
          2.11584680e-02, -6.13879040e-03,  6.09459728e-03,
         -2.07377560e-02, -1.29706636e-02,  3.82832922e-02,
         -3.01131494e-02],
        [ 3.72535698e-02, -3.19940932e-02, -3.32688466e-02,
         -9.31788236e-04, -2.33863592e-02,  1.61160268e-02,
         -4.68723774e-02, -2.52453685e-02, -3.309035

In [ ]:
embedded_docs[0]

In [19]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[ 0.00940508, -0.04408766, -0.02817686,  0.02115847, -0.00613879,
         0.0060946 , -0.02073776, -0.01297066,  0.03828329, -0.03011315],
       [ 0.00940508, -0.04408766, -0.02817686,  0.02115847, -0.00613879,
         0.0060946 , -0.02073776, -0.01297066,  0.03828329, -0.03011315],
       [ 0.00940508, -0.04408766, -0.02817686,  0.02115847, -0.00613879,
         0.0060946 , -0.02073776, -0.01297066,  0.03828329, -0.03011315],
       [ 0.00940508, -0.04408766, -0.02817686,  0.02115847, -0.00613879,
         0.0060946 , -0.02073776, -0.01297066,  0.03828329, -0.03011315],
       [ 0.03725357, -0.03199409, -0.03326885, -0.00093179, -0.02338636,
         0.01611603, -0.04687238, -0.02524537, -0.03309035,  0.02429355],
       [-0.03998597, -0.03151499, -0.02351085,  0.00227885, -0.03740642,
         0.04144246,  0.03917508, -0.0197734 ,  0.02098032, -0.02004621],
       [ 0.00062867,  0.0434331 ,  0.00206816, -0.00572865,  0.02246096,
         0.01973606, -0.01485807, -0.0117605 

### IMDB TEXT CLASSIFICATION END-TO-END PROJECT

In [22]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense


In [23]:
# dataset
max_features = 10000
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

print(f'training data shape: {x_train.shape}, Training labels shape: {y_train.shape}')
print(f'testing data shape: {x_test.shape}, Testing labels shape: {y_test.shape}')

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
training data shape: (25000,), Training labels shape: (25000,)
testing data shape: (25000,), Testing labels shape: (25000,)


In [29]:
sample_review= x_train[0],
sample_label= y_train[0]
print(sample_review)
print(sample_label)

([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32],)
1


In [32]:
word_index=imdb.get_word_index()
word_index
reverse_word_index=dict([(value,key) for (key,value) in word_index.items()])
reverse_word_index

{34701: 'fawn',
 52006: 'tsukino',
 52007: 'nunnery',
 16816: 'sonja',
 63951: 'vani',
 1408: 'woods',
 16115: 'spiders',
 2345: 'hanging',
 2289: 'woody',
 52008: 'trawling',
 52009: "hold's",
 11307: 'comically',
 40830: 'localized',
 30568: 'disobeying',
 52010: "'royale",
 40831: "harpo's",
 52011: 'canet',
 19313: 'aileen',
 52012: 'acurately',
 52013: "diplomat's",
 25242: 'rickman',
 6746: 'arranged',
 52014: 'rumbustious',
 52015: 'familiarness',
 52016: "spider'",
 68804: 'hahahah',
 52017: "wood'",
 40833: 'transvestism',
 34702: "hangin'",
 2338: 'bringing',
 40834: 'seamier',
 34703: 'wooded',
 52018: 'bravora',
 16817: 'grueling',
 1636: 'wooden',
 16818: 'wednesday',
 52019: "'prix",
 34704: 'altagracia',
 52020: 'circuitry',
 11585: 'crotch',
 57766: 'busybody',
 52021: "tart'n'tangy",
 14129: 'burgade',
 52023: 'thrace',
 11038: "tom's",
 52025: 'snuggles',
 29114: 'francesco',
 52027: 'complainers',
 52125: 'templarios',
 40835: '272',
 52028: '273',
 52130: 'zaniacs',

In [36]:
decoded_review = ' '.join([reverse_word_index.get(i - 3, '?') for i in sample_review[0]])
decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [40]:
from re import X
from tensorflow.keras.preprocessing.sequence import pad_sequences
max_length = 500
x_train = sequence.pad_sequences(x_train, maxlen=max_length)
x_test = sequence.pad_sequences(x_test, maxlen=max_length)
x_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

### RNN MODEL


In [45]:
model = Sequential()
model.add(Embedding(max_features, 128, input_length=max_length))
model.add(SimpleRNN(128,activation= 'relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_2 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [46]:
## early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping=EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)


In [47]:
model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2, callbacks=[early_stopping])

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 164s 259ms/step - accuracy: 0.5934 - loss: 12.9259 - val_accuracy: 0.7770 - val_loss: 0.4675
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 203s 261ms/step - accuracy: 0.8478 - loss: 0.3562 - val_accuracy: 0.8300 - val_loss: 0.3897
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 201s 260ms/step - accuracy: 0.9052 - loss: 0.2476 - val_accuracy: 0.8376 - val_loss: 0.4067
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 201s 258ms/step - accuracy: 0.8563 - loss: 0.4088 - val_accuracy: 0.7964 - val_loss: 0.4555
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 202s 258ms/step - accuracy: 0.9019 - loss: 0.2463 - val_accuracy: 0.8010 - val_loss: 0.4661


### SENTIMENT ANALYSIS/ MODEL WORKING

In [48]:
model.save('simple_rnn_imdb.h5')

In [49]:
from tensorflow.keras.models import load_model

In [50]:
model = load_model('simple_rnn_imdb.h5')
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)              │ (32, 500, 128)              │       1,280,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_2 (SimpleRNN)             │ (32, 128)                   │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (32, 1)                     │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,313,027 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [52]:

def decode_review(encoded_review):
    return ' '.join([reverse_word_index.get(i - 3, '?') for i in encoded_review])


def preprocess_text(text):
    words = text.lower().split()
    encoded_review = [word_index.get(word, 2) + 3 for word in words]
    padded_review = sequence.pad_sequences([encoded_review], maxlen=500)
    return padded_review

In [53]:


def predict_sentiment(review):
    preprocessed_input=preprocess_text(review)

    prediction=model.predict(preprocessed_input)

    sentiment = 'Positive' if prediction[0][0] > 0.5 else 'Negative'

    return sentiment, prediction[0][0]

In [54]:
# Step 4: User Input and Prediction
# Example review for prediction
example_review = "This movie was fantastic! The acting was great and the plot was thrilling."

sentiment,score=predict_sentiment(example_review)

print(f'Review: {example_review}')
print(f'Sentiment: {sentiment}')
print(f'Prediction Score: {score}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step
Review: This movie was fantastic! The acting was great and the plot was thrilling.
Sentiment: Positive
Prediction Score: 0.9537490606307983


STREAMLIT APP

In [55]:
! pip install streamlit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 61.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 67.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 5.6 MB/s eta 0:00:00


In [57]:
import streamlit as st
st.title('IMDB movie review sentiment analysis')
st.write('enter a movie review to classify it as a positive or negative review')
user_input = st.text_area('movie review')
if st.button('classify'):
  preprocessed_input=preprocess_text(user_input)
  sentiment= 'positive' if model.predict(preprocessed_input)[0][0] > 0.5 else 'negative'
  st.write(f'sentiment: {sentiment}')
  st.write(f'prediction score: {model.predict(preprocessed_input)[0][0]}')
else:
    st.write('please enter a movie review')


2025-04-04 17:22:05.576 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-04 17:22:05.800 
  command:

    streamlit run /usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2025-04-04 17:22:05.801 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-04 17:22:05.804 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-04 17:22:05.805 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-04 17:22:05.806 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-04 17:22:05.807 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-04 17:22:05.808 Thread 'MainThread': mi

In [63]:
!wget -q -O - ipv4.icanhazip.com

34.169.71.244


In [64]:
! streamlit run /content/app_py.py & npx localtunnel --port 8501



⠙⠹⠸⠼⠴
  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.169.71.244:8501

⠦your url is: https://social-women-see.loca.lt
────────────────────────── Traceback (most recent call last) ───────────────────────────
  /usr/local/lib/python3.11/dist-packages/streamlit/runtime/scriptrunner/exec_code.py:  
  121 in exec_func_with_error_handling                                                  
                                                                                        
  /usr/local/lib/python3.11/dist-packages/streamlit/runtime/scriptrunner/script_runner  
  .py:640 in code_to_exec                                                               
                                                                                        
  /content/app_py.py:15 in <module>                                                     
                                                            